version: '3.4'
services:
    
    dev:
        container_name: rchain-dev
        image: rchain-dev-image
        build: .
        volumes:
          # Preserve dev home
            - type: volume
              source: dev-home
              target: /home/dev
          # Bind to host docker to prevent containers in containers
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
          # Bind to X session to start GUI apps
            - type: bind
              source: /tmp/.X11-unix
              target: /tmp/.X11-unix
            - type: bind
              source: /tmp/.docker.xauth
              target: /tmp/.docker.xauth
        tty: true
        network_mode: "host"

volumes:
    dev-home:
