version: '3'
services:
    
    dev:
        container_name: livelygig-dev
        build: .
        image: livelygig-dev-image
        # Preserve dev home and ssh keys
        volumes:
         - livelygig-dev-home:/home/dev
         - type: bind
           source: /tmp/.X11-unix
           target: /tmp/.X11-unix
         - type: bind
           source: /tmp/.docker.xauth
           target: /tmp/.docker.xauth
        tty: true

volumes:
    livelygig-dev-home:
