version: '3'
services:
    
    dev:
        container_name: livelygig-dev
        build: .
        image: livelygig-dev-image
        # Preserve dev home and ssh keys
        volumes:
         - livelygig-dev-home:/home/dev
        tty: true

volumes:
    livelygig-dev-home:
