version: '3.4'
services:
    
    dev:
        container_name: livelygig-dev
        build: .
        image: livelygig-dev-image
        # Preserve dev home and ssh keys
        volumes:
            - type: volume
              source: livelygig-dev-home
              target: /home/dev
            - type: bind
              source: /tmp/.X11-unix
              target: /tmp/.X11-unix
            - type: bind
              source: /tmp/.docker.xauth
              target: /tmp/.docker.xauth
        tty: true
        network_mode: "host"

volumes:
    livelygig-dev-home:
